version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r $CODEBUILD_SRC_DIR/requirements.txt

  pre_build:
    commands:
      - echo "Verifying Python version..."
      - python --version
      - echo "Setting up Django environment..."
      - export DJANGO_SETTINGS_MODULE=restaurent.settings
      - echo "Running pylint..."
      - pylint $CODEBUILD_SRC_DIR/*.py > pylint-report-root.txt || echo "Pylint failed on root"
      - pylint $CODEBUILD_SRC_DIR/restaurent/*.py > pylint-report-restaurant.txt || echo "Pylint failed on restaurant"
      - pylint $CODEBUILD_SRC_DIR/staff/*.py > pylint-staff.txt || echo "Pylint failed on complaints"
      - cat pylint-report-root.txt pylint-report-restaurant.txt pylint-staff.txt > pylint-report.txt
      - echo "Running pytest..."
      - pytest --maxfail=1 --disable-warnings > pytest-report.txt || echo "Pytest failed"

  build:
    commands:
      - echo "Running SonarCloud scan..."
      - /opt/sonar-scanner/bin/sonar-scanner -X -Dsonar.login=$SONAR_TOKEN
      - echo "Contents of requirements.txt:"
      - cat "$CODEBUILD_SRC_DIR/requirements.txt"
      - echo "Running OWASP Dependency-Check..."
      - /opt/dependency-check/bin/dependency-check.sh --project "Django Project" --scan "$CODEBUILD_SRC_DIR/" --out ./dependency-check-report --data "$CODEBUILD_SRC_DIR/nvd-cache" --log dependency-check.log  --nvdApiKey 9a2f5fda-a545-4181-928d-fdc2aeb36133
      - echo "Build, SonarCloud scan, and Dependency-Check completed"
      - echo "Creating application zip (excluding reports)..."
      - zip -r app.zip * -x pylint-report*.txt pytest-report.txt dependency-check-report/*  # Exclude report files from the app.zip

artifacts:
  files:
    - app.zip  # Only include the application zip here
    - pylint-report*.txt  # Include the pylint report files separately
    - pytest-report.txt   # Include the pytest report separately
    - dependency-check-report/**/*  # Include the dependency check report separately

cache:
  paths:
    - '$CODEBUILD_SRC_DIR/nvd-cache/**/*'
